-- Legiscore Scorecards backup for `lsf`
-- Generated: 2026-09-12 04:38:32 UTC

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `housebillvotes`;
CREATE TABLE `housebillvotes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `year` int NOT NULL,
  `session` varchar(2) NOT NULL,
  `bill` varchar(5) NOT NULL,
  `result` varchar(11) NOT NULL DEFAULT 'none',
  `section` varchar(255) NOT NULL DEFAULT '',
  `objection` varchar(255) NOT NULL DEFAULT '',
  `ecresult` varchar(11) NOT NULL DEFAULT 'none',
  `ecsection` varchar(255) NOT NULL DEFAULT '',
  `ecobjection` varchar(255) NOT NULL DEFAULT '',
  `taresult` varchar(11) NOT NULL DEFAULT 'none',
  `tasection` varchar(255) NOT NULL DEFAULT '',
  `taobjection` varchar(255) NOT NULL DEFAULT '',
  `taecresult` varchar(11) NOT NULL DEFAULT 'none',
  `taecsection` varchar(255) NOT NULL DEFAULT '',
  `taecobjection` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `YSB` (`year`,`session`,`bill`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=227 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('1', '2025', 'R', '32', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('2', '2025', 'R', '33', 'reject', '161.264(6)', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('3', '2025', 'R', '37', 'reject', '226.8860', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('4', '2025', 'R', '42', 'autmodo', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('5', '2025', 'R', '44', 'reject', '143.1240', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('6', '2025', 'R', '49', 'autmodo', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('7', '2025', 'R', '56', 'reject', '332.700', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('8', '2025', 'R', '58', 'reject', '324.263', 'A1S10', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('9', '2025', 'R', '68', 'reject', '516.140(3)', 'A1S1 A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('10', '2025', 'R', '73', 'reject', '79.235', 'A3S42', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('11', '2025', 'R', '75', 'reject', '1.810', 'Codified A1S5', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('12', '2025', 'R', '87', 'reject', '557.520', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('13', '2025', 'R', '105', 'reject', 'Section 1.1 (Line 187)', '10th Amendment USCON', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('14', '2025', 'R', '121', 'accept', '', '', '', '', '', 'reject', '135.315', 'A3S21', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('15', '2025', 'R', '122', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('16', '2025', 'R', '126', 'reject', '105.695', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('17', '2025', 'R', '134', 'reject', '650.9', '10th Amendment USCON', 'reject', 'SECTION B', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('18', '2025', 'R', '138', 'reject', '301.469', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('19', '2025', 'R', '145', 'reject', '610.021(29)', 'A3S23', '', '', '', 'reject', '476.1300', 'A3S21', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('20', '2025', 'R', '147', 'reject', '70.655', 'A3S23', '', '', '', 'reject', '57.280', 'A3S21', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('21', '2025', 'R', '169', 'autmodo', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('22', '2025', 'R', '176', 'reject', '193.265', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('23', '2025', 'R', '177', 'reject', '208.152(16)', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('24', '2025', 'R', '183', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('25', '2025', 'R', '195', 'reject', '188.035', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('26', '2025', 'R', '199', 'accept', '', '', '', '', '', 'reject', '50.8150', 'A3S23', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('27', '2025', 'R', '200', 'reject', '67.1754', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('28', '2025', 'R', '202', 'reject', '288.050(3)', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('29', '2025', 'R', '205', 'reject', '87.140', 'A3S40(30)', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('30', '2025', 'R', '207', 'reject', '136.055(1)', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('31', '2025', 'R', '225', 'reject', '44.087(3)', 'A1S2', '', '', '', 'reject', '57.2800', 'A3S21', 'reject', 'SECTION B', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('32', '2025', 'R', '232', 'reject', '160.663', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('33', '2025', 'R', '233', 'reject', '64.231(1)', 'A1S1 A1S2 A1S3', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('34', '2025', 'R', '243', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('35', '2025', 'R', '247', 'reject', '301.020(2)', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('36', '2025', 'R', '262', 'reject', '191.261', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('37', '2025', 'R', '267', 'reject', '168.025', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('38', '2025', 'R', '268', 'reject', '168.014', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('39', '2025', 'R', '269', 'reject', '135.131', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('40', '2025', 'R', '296', 'accept', '', '', '', '', '', 'reject', '168.036', 'A3S21', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('41', '2025', 'R', '313', 'autmodo', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('42', '2025', 'R', '325', 'reject', '192.251', 'A1S13', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('43', '2025', 'R', '326', 'reject', '67.300', 'A3S39', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('44', '2025', 'R', '328', 'reject', '571.107(3)', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('45', '2025', 'R', '331', 'reject', '173.836', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('46', '2025', 'R', '339', 'accept', '', '', 'reject', 'SECTION B', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('47', '2025', 'R', '344', 'reject', '407.932', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('48', '2025', 'R', '352', 'reject', '50.815(1)', 'A1S9', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('49', '2025', 'R', '369', 'autmodo', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('50', '2025', 'R', '378', 'reject', '301.469(4)', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('51', '2025', 'R', '388', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('52', '2025', 'R', '397', 'reject', '324.1835', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('53', '2025', 'R', '408', 'reject', '160.664', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('54', '2025', 'R', '416', 'reject', '160.660', '10th Amendment USCON', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('55', '2025', 'R', '419', 'autmodo', '', '', '', '', '', 'reject', '172.345', 'A3S21', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('56', '2025', 'R', '437', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('57', '2025', 'R', '478', 'reject', '331.084', 'A1S10', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('58', '2025', 'R', '489', 'reject', '578.018(2)', 'A1S3', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('59', '2025', 'R', '493', 'reject', '144.812', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('60', '2025', 'R', '495', 'reject', '84.012', 'A1S2', '', '', '', 'reject', '84.012', 'A3S23', 'reject', 'SECTION B', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('61', '2025', 'R', '497', 'accept', '', '', 'accept', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('62', '2025', 'R', '499', 'reject', '92.205', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('63', '2025', 'R', '507', 'reject', '115.635', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('64', '2025', 'R', '513', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('65', '2025', 'R', '516', 'accept', '', '', '', '', '', 'accept', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('66', '2025', 'R', '520', 'reject', '105.963', 'A1S1/S2/S3', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('67', '2025', 'R', '538', 'reject', '168.133(1)', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('68', '2025', 'R', '543', 'reject', '632.305', 'A1S2/S3', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('69', '2025', 'R', '544', 'reject', '281.260(10)', '10th Amendment USCON', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('70', '2025', 'R', '563', 'reject', '252.047(2)', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('71', '2025', 'R', '565', 'reject', '537.325(7)', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('72', '2025', 'R', '567', 'reject', '290.502', 'A3S23', 'reject', 'SECTION B', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('73', '2025', 'R', '572', 'reject', '68.080', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('74', '2025', 'R', '575', 'reject', '116.332', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('75', '2025', 'R', '594', 'accept', '', '', '', '', '', 'accept', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('76', '2025', 'R', '595', 'reject', '441.043', 'A1S13', '', '', '', 'reject', '441.043', 'A1S13', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('77', '2025', 'R', '596', 'autmodo', '', '', '', '', '', 'autmodo', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('78', '2025', 'R', '606', 'reject', '172.640', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('79', '2025', 'R', '607', 'reject', '160.518', 'A3S21', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('80', '2025', 'R', '608', 'autmodo', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('81', '2025', 'R', '615', 'reject', '492.304(5)', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('82', '2025', 'R', '618', 'reject', '376.2102', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('83', '2025', 'R', '629', 'autmodo', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('84', '2025', 'R', '643', 'reject', '311.094(2)(a)', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('85', '2025', 'R', '660', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('86', '2025', 'R', '661', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('87', '2025', 'R', '707', 'reject', '130.021', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('88', '2025', 'R', '709', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('89', '2025', 'R', '711', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('90', '2025', 'R', '735', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('91', '2025', 'R', '736', 'reject', '455.513(1)(2)', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('92', '2025', 'R', '737', 'reject', '210.110(1)', '9th Amendment USCON', '', '', '', 'reject', '210.1012', 'A1S2', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('93', '2025', 'R', '742', 'reject', '1.2030(2)(2)', '10th Amendment USCON', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('94', '2025', 'R', '754', 'reject', '362.020', 'A1S1', '', '', '', 'reject', '32.115', 'A3S38(A)', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('95', '2025', 'R', '757', 'reject', '407.313', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('96', '2025', 'R', '765', 'reject', '333.041', 'A3S28', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('97', '2025', 'R', '770', 'reject', 'Entirety', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('98', '2025', 'R', '780', 'reject', '137.115(17)(3)', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('99', '2025', 'R', '794', 'reject', '115.163', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('100', '2025', 'R', '798', 'reject', '135.600(2)', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('101', '2025', 'R', '799', 'reject', '32.056', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('102', '2025', 'R', '810', 'reject', '227.881', 'A1S1/S2', '', '', '', 'reject', '227.881', 'A1S1/S2', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('103', '2025', 'R', '816', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('104', '2025', 'R', '825', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('105', '2025', 'R', '828', 'reject', '143.511', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('106', '2025', 'R', '834', 'reject', '324.263', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('107', '2025', 'R', '835', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('108', '2025', 'R', '837', 'reject', '251.034', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('109', '2025', 'R', '850', 'reject', '210.221(3)(2)', 'A1S2/S15', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('110', '2025', 'R', '875', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('111', '2025', 'R', '903', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('112', '2025', 'R', '918', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('113', '2025', 'R', '927', 'reject', '9.411', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('114', '2025', 'R', '937', 'reject', '160.014', 'Codified A1S5', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('115', '2025', 'R', '939', 'reject', '67.280(4)', 'A1S13', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('116', '2025', 'R', '943', 'reject', '96.192(1)(1)', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('117', '2025', 'R', '952', 'reject', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('118', '2025', 'R', '969', 'reject', '301.140', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('119', '2025', 'R', '970', 'reject', '572.100', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('120', '2025', 'R', '971', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('121', '2025', 'R', '974', 'reject', '317.400', 'A3S23', '', '', '', 'reject', '375.1402', 'A3S23', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('122', '2025', 'R', '991', 'reject', '407.324', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('123', '2025', 'R', '992', 'reject', '190.106', 'A3S40(30)', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('124', '2025', 'R', '999', 'reject', '138.425', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('125', '2025', 'R', '1037', 'reject', '196.1170(5)', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('126', '2025', 'R', '1041', 'reject', '311.2026', 'A3S23', '', '', '', 'reject', '311.2026', 'A3S40(30)', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('127', '2025', 'R', '1049', 'autmodo', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('128', '2025', 'R', '1086', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('129', '2025', 'R', '1116', 'reject', '272.138', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('130', '2025', 'R', '1122', 'autmodo', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('131', '2025', 'R', '1175', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('132', '2025', 'R', '1218', 'accept', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('133', '2025', 'R', '1259', 'reject', '478.700', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('134', '2025', 'R', '1264', 'reject', '67.486', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('135', '2025', 'R', '1284', 'reject', '229.222', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('136', '2025', 'R', '1298', 'reject', '192.2405', 'A3S23', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('137', '2025', 'R', '1346', 'reject', '68.010', 'A1S1', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('138', '2025', 'R', '1363', 'reject', '160.421', 'A1S2', '', '', '', '', '', '', '', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('139', '2025', 'R', '1464', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('140', '2025', 'R', '1524', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('141', '2026', 'R', '1623', 'reject', '324.263', 'A1S10', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('142', '2026', 'R', '1840', 'accept', '', '', 'reject', 'Section B', '', 'reject', '209.247', 'A3S21/23', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('143', '2026', 'R', '1625', 'reject', '579.022', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('144', '2026', 'R', '1628', 'reject', '23.295', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('145', '2026', 'R', '1644', 'reject', '285.075', '10th Amendment USCON', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('146', '2026', 'R', '1663', 'reject', '163.048', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('147', '2026', 'R', '1664', 'reject', '516.130', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('148', '2026', 'R', '1667', 'reject', '188.035', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('149', '2026', 'R', '1694', 'accept', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('150', '2026', 'R', '1696', 'reject', '194.119', 'A3S23', 'none', '', '', 'reject', '210.1700', 'A3S21/23', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('151', '2026', 'R', '1707', 'reject', '144.010', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('152', '2026', 'R', '1717', 'reject', '191.479', 'A1S2', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('153', '2026', 'R', '1718', 'reject', '537.610', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('154', '2026', 'R', '1740', 'reject', '577.010', 'A1S2', 'none', '', '', 'reject', '302.304', 'A1S2', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('155', '2026', 'R', '1749', 'reject', '34.069', 'A1S2', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('156', '2026', 'R', '1756', 'reject', '9.501', 'A1S1', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('157', '2026', 'R', '1757', 'reject', '167.720', 'A1S2', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('158', '2026', 'R', '1766', 'reject', '137.073', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('159', '2026', 'R', '1768', 'reject', '137.016', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('160', '2026', 'R', '1783', 'reject', '192.021', '10th Amendment USCON', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('161', '2026', 'R', '1786', 'reject', '43.265', 'A1S1/S3', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('162', '2026', 'R', '1788', 'reject', '130.031', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('163', '2026', 'R', '1790', 'reject', '137.067', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('164', '2026', 'R', '1791', 'reject', '67.491', 'A3S1', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('165', '2026', 'R', '1797', 'reject', '326.277', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('166', '2026', 'R', '1800', 'reject', '138.390', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('167', '2026', 'R', '1812', 'accept', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('168', '2026', 'R', '1825', 'reject', '50.333', 'A1S2', 'none', '', '', 'reject', '48.020', 'A3S23', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('169', '2026', 'R', '1826', 'reject', '167.627', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('170', '2026', 'R', '1827', 'reject', '301.142', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('171', '2026', 'R', '1838', 'reject', '301.132', 'A1S2', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('172', '2026', 'R', '1839', 'reject', '407.3405', 'A1S1/A3S23', 'none', '', '', 'reject', '407.3405', 'A1S1', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('173', '2026', 'R', '1844', 'reject', '334.1921', 'A1S1-3', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('174', '2026', 'R', '1847', 'reject', '332.705', 'A3S1', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('175', '2026', 'R', '1855', 'reject', '192.020', 'A1S1', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('176', '2026', 'R', '1866', 'reject', '590.100', 'A3S23', 'none', '', '', 'reject', '160.665', 'A3S40/41/42', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('177', '2026', 'R', '1867', 'reject', '67.1000', 'A1S2', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('178', '2026', 'R', '1870', 'reject', '525.235', 'A1S10', 'none', '', '', 'reject', '513.380', 'A1S10', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('179', '2026', 'R', '1871', 'reject', '9.515', 'A1S2', 'none', '', '', 'reject', '9.515', 'A1S2', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('180', '2026', 'R', '1883', 'reject', '144.030', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('181', '2026', 'R', '1885', 'reject', '644.021', 'A1S1', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('182', '2026', 'R', '1908', 'reject', '452.305', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('183', '2026', 'R', '1917', 'reject', '247.181', 'A1S2', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('184', '2026', 'R', '1919', 'reject', '143.591', 'A1S2', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('185', '2026', 'R', '1940', 'reject', '493.050', 'A3S23', 'none', '', '', 'reject', '108.240', 'A1S21/23', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('186', '2026', 'R', '1948', 'reject', '9.411', 'A1S2', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('187', '2026', 'R', '1961', 'reject', '324.214', 'A3S1', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('188', '2026', 'R', '1963', 'reject', '337.600', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('189', '2026', 'R', '1977', 'reject', '632.305', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('190', '2026', 'R', '1980', 'reject', '190.174', 'A1S1', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('191', '2026', 'R', '2033', 'reject', '191.1720', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('192', '2026', 'R', '2035', 'reject', '407.3007', 'A1S1', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('193', '2026', 'R', '2057', 'reject', '311.083', 'A1S2', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('194', '2026', 'R', '2061', 'reject', '160.014', 'A1S5', 'none', '', '', 'reject', '160.014', 'A1S5', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('195', '2026', 'R', '2085', 'accept', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('196', '2026', 'R', '2097', 'reject', '178.530', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('197', '2026', 'R', '2145', 'reject', '226.540', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('198', '2026', 'R', '2167', 'reject', '21.158', 'A1S21/23', 'reject', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('199', '2026', 'R', '2178', 'reject', '115.240', 'A3S21', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('200', '2026', 'R', '2180', 'reject', '32.058', 'A1S1', 'none', '', '', 'reject', '32.058', 'A1S1', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('201', '2026', 'R', '2189', 'reject', '136.055', 'A1S2', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('202', '2026', 'R', '2273', 'reject', '566.152', 'A3S21', 'none', '', '', 'reject', '27.117', 'A3S23', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('203', '2026', 'R', '2274', 'reject', '168.046', 'A3S1', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('204', '2026', 'R', '2384', 'reject', '67.486', 'A3S1', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('205', '2026', 'R', '2423', 'reject', '408.500', 'A1S2/A3S1', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('206', '2026', 'R', '1730', 'reject', '571.010', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('207', '2026', 'R', '1772', 'reject', '453.073', 'A1S2', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('208', '2026', 'R', '1869', 'reject', '42.303', 'A3S1', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('209', '2026', 'R', '2069', 'reject', '304.920', 'A1S2', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('210', '2026', 'R', '2096', 'reject', '251.034', 'A1S2', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('211', '2026', 'R', '2099', 'reject', '534.602', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('212', '2026', 'R', '2103', 'reject', '59.120', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('213', '2026', 'R', '2105', 'reject', '386.021', 'A1S2', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('214', '2026', 'R', '1736', 'reject', '67.1754', 'A3S40/41/42', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('215', '2026', 'R', '1758', 'autmodo', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('216', '2026', 'R', '1887', 'reject', '407.3475', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('217', '2026', 'R', '1906', 'reject', '139.053', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('218', '2026', 'R', '2108', 'accept', '', '', 'none', '', '', 'accept', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('219', '2026', 'R', '2120', 'reject', '160.775', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('220', '2026', 'R', '2122', 'reject', '393.1250', 'A3S1', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('221', '2026', 'R', '2125', 'reject', '115.158', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('222', '2026', 'R', '2142', 'reject', '135.750', 'A1S2', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('223', '2026', 'R', '2146', 'reject', '206.158', 'A1S1', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('224', '2026', 'R', '2151', 'reject', '173.2553', 'A1S1', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('225', '2026', 'R', '2230', 'reject', '186.085', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `housebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('226', '2026', 'R', '2292', 'reject', '192.2405', 'A3S23', 'none', '', '', 'none', '', '', 'none', '', '');

DROP TABLE IF EXISTS `senatebillvotes`;
CREATE TABLE `senatebillvotes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `year` int NOT NULL,
  `session` varchar(2) NOT NULL,
  `bill` varchar(5) NOT NULL,
  `result` varchar(11) NOT NULL DEFAULT 'none',
  `section` varchar(255) NOT NULL DEFAULT '',
  `objection` varchar(255) NOT NULL DEFAULT '',
  `ecresult` varchar(11) NOT NULL DEFAULT 'none',
  `ecsection` varchar(255) NOT NULL DEFAULT '',
  `ecobjection` varchar(255) NOT NULL DEFAULT '',
  `taresult` varchar(11) NOT NULL DEFAULT 'none',
  `tasection` varchar(255) NOT NULL DEFAULT '',
  `taobjection` varchar(255) NOT NULL DEFAULT '',
  `taecresult` varchar(11) NOT NULL DEFAULT 'none',
  `taecsection` varchar(255) NOT NULL DEFAULT '',
  `taecobjection` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `YSB` (`year`,`session`,`bill`)
) ENGINE=MyISAM AUTO_INCREMENT=55 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('1', '2025', 'R', '59', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('2', '2025', 'R', '81', 'reject', '', '', 'none', '', '', 'reject', '', '', 'reject', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('3', '2025', 'R', '1', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('4', '2025', 'R', '2', 'accept', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('5', '2025', 'R', '3', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('6', '2025', 'R', '60', 'accept', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('7', '2025', 'R', '4', 'reject', '', '', 'reject', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('8', '2025', 'R', '7', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('9', '2025', 'R', '10', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('10', '2025', 'R', '22', 'reject', '', '', 'reject', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('11', '2025', 'R', '28', 'reject', '', '', 'none', '', '', 'reject', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('12', '2025', 'R', '35', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('13', '2025', 'R', '38', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('14', '2025', 'R', '40', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('15', '2025', 'R', '43', 'reject', '', '', 'none', '', '', 'reject', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('16', '2025', 'R', '47', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('17', '2025', 'R', '49', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('18', '2025', 'R', '50', 'reject', '', '', 'reject', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('19', '2025', 'R', '105', 'accept', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('20', '2025', 'R', '125', 'accept', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('21', '2025', 'R', '133', 'accept', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('22', '2025', 'R', '152', 'autmodo', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('23', '2025', 'R', '166', 'accept', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('24', '2025', 'R', '189', 'autmodo', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('25', '2025', 'R', '218', 'accept', '', '', 'none', '', '', 'reject', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('26', '2025', 'R', '221', 'accept', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('27', '2025', 'R', '266', 'autmodo', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('28', '2025', 'R', '360', 'autmodo', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('29', '2025', 'R', '396', 'autmodo', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('30', '2025', 'R', '466', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('31', '2025', 'R', '348', 'reject', '', '', 'none', '', '', 'reject', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('32', '2025', 'R', '110', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('33', '2025', 'R', '61', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('34', '2025', 'R', '63', 'reject', '', '', 'none', '', '', 'reject', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('35', '2025', 'R', '66', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('36', '2025', 'R', '67', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('37', '2025', 'R', '68', 'reject', '', '', 'none', '', '', 'reject', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('38', '2025', 'R', '71', 'reject', '', '', 'none', '', '', 'reject', '', '', 'reject', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('39', '2025', 'R', '79', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('40', '2025', 'R', '80', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('41', '2025', 'R', '82', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('42', '2025', 'R', '94', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('43', '2025', 'R', '97', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('44', '2025', 'R', '98', 'reject', '', '', 'none', '', '', 'reject', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('45', '2025', 'R', '111', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('46', '2025', 'R', '120', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('47', '2025', 'R', '145', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('48', '2025', 'R', '150', 'reject', '', '', 'none', '', '', 'reject', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('49', '2025', 'R', '156', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('50', '2025', 'R', '160', 'reject', '', '', 'none', '', '', 'reject', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('51', '2025', 'R', '163', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('52', '2025', 'R', '167', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('53', '2025', 'R', '271', 'reject', '', '', 'none', '', '', 'none', '', '', 'none', '', '');
INSERT INTO `senatebillvotes` (`id`, `year`, `session`, `bill`, `result`, `section`, `objection`, `ecresult`, `ecsection`, `ecobjection`, `taresult`, `tasection`, `taobjection`, `taecresult`, `taecsection`, `taecobjection`) VALUES ('54', '2026', 'R', '1196', 'none', '', '', 'reject', 'SECTION B', '', 'none', '', '', 'none', '', '');

SET FOREIGN_KEY_CHECKS=1;
